# Sync with: .github/workflows/sync-labels.yml
# Format: https://github.com/crazy-max/ghaction-github-labeler

- name: P0
  color: d73a4a
  description: Bloqueante para el MVP

- name: P1
  color: f66a0a
  description: Alta prioridad

- name: P2
  color: fbca04
  description: Prioridad normal

- name: Tipo:Bug
  color: d73a4a
  description: Incidencia o comportamiento incorrecto

- name: Tipo:Feature
  color: 0e8a16
  description: Nueva funcionalidad

- name: Tipo:Task
  color: 0366d6
  description: Tarea técnica / chore

- name: Tipo:CI
  color: 5319e7
  description: Infra de CI/CD

- name: Capa:Contrato
  color: 0b7285
  description: Capas 0–3 (naming, schemas, firma)

- name: Capa:Front
  color: 0969da
  description: UI/UX del wizard/flow

- name: Capa:Admin
  color: 8250df
  description: Panel WP, publicación, pricing

- name: Capa:Schemas
  color: 1f6feb
  description: JSON Schemas, fixtures y validaciones

- name: Capa:Viewer
  color: 218bff
  description: Visor 3D / bridge

- name: Capa:WP-Plugin
  color: 54aeff
  description: Plugin WordPress unificado

- name: Capa:Assets
  color: a371f7
  description: GLB/KTX2, presupuestos, linter

- name: Capa:CI
  color: 8957e5
  description: Workflows y utilidades de CI/CD

- name: Capa:Docs
  color: 8b949e
  description: Documentación (Capas 0–5, guías)
