name: Repo · Sync labels
on:
  push:
    paths: [ '.github/labels.yml', '.github/workflows/sync-labels.yml' ]
  workflow_dispatch:
jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml_file: .github/labels.yml
          # remove-others true para limpiar etiquetas no usadas
          dry_run: false
