name: ✨ Feature
description: Solicitar nueva funcionalidad
title: "[FEAT] "
labels: ["Tipo:Feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Resumen
      description: ¿Qué quieres que haga el sistema y por qué?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      description: Define "done".
      placeholder: 1) ... 2) ... 3) ...
  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options: [P0, P1, P2]
