name: CI · Assets

on:
  pull_request: {}          # corre en cualquier PR (evita "Expected")
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Show versions
        run: node -v && npm -v

      - name: Install deps (lock optional)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Lint assets
        run: node tools/assets-lint/lint.mjs assets
