name: CI · PHPStan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: json, mbstring

      # Si no hay phpstan.neon en el repo, crea uno razonable para WP
      - name: Prepare phpstan config (if missing)
        run: |
          if [ ! -f phpstan.neon ]; then
            cat > phpstan.neon <<'NEON'
            parameters:
              level: 0
              paths:
                - apps/wp-plugin/G3D-Flow-Orchestrator
              excludePaths:
                - */vendor/*
                - */node_modules/*
              ignoreErrors:
                - '#Call to unknown function (add_action|add_filter|register_post_type|wp_enqueue_script)#'
            NEON
          fi

      - name: Download PHPStan (phar)
        run: curl -sL https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar -o phpstan.phar

      - name: Run PHPStan
        run: php phpstan.phar analyse -c phpstan.neon --no-progress --memory-limit=1G

    
 

