name: CI · PHP
on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Lint PHP
        run: |
          set -euo pipefail
          find apps/wp-plugin -type f -name "*.php" -print0 | xargs -0 -n1 -P 4 php -l
