name: CI · PHPStan

on:
  pull_request:
    paths:
      - 'apps/wp-plugin/**'
  push:
    branches: [main]
    paths:
      - 'apps/wp-plugin/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    # continue-on-error: true  # <- opcional, si no quieres que bloquee merges
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install dev deps
        working-directory: apps/wp-plugin/G3D-Flow-Orchestrator
        run: |
          composer config --no-plugins allow-plugins.phpstan/extension-installer true
          composer update --no-interaction --no-progress
          composer show -D

      - name: Run PHPStan
        working-directory: apps/wp-plugin/G3D-Flow-Orchestrator
        run: vendor/bin/phpstan analyse -c phpstan.neon --no-progress --memory-limit=1G
