name: Release · WP plugin artifact

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing release tag (e.g., v0.1.1)'
        required: true

permissions:
  contents: write

jobs:
  package-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # opcional, pero recomendado

      - name: Resolve tag (manual or from release)
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Create plugin zip
        run: |
          PLUGDIR="apps/wp-plugin/G3D-Flow-Orchestrator"
          OUT="g3d-flow-orchestrator-${TAG}.zip"
          cd "$PLUGDIR/.."
          # crea el zip en la RAÍZ del repo
          zip -r "$GITHUB_WORKSPACE/$OUT" "G3D-Flow-Orchestrator" -x "**/.git/**"
          echo "ZIP_PATH=$GITHUB_WORKSPACE/$OUT" >> $GITHUB_ENV

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: ${{ env.ZIP_PATH }}
          fail_on_unmatched_files: true

