name: Release · WP plugin artifact

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing release tag (e.g., v0.1.2)'
        required: true

permissions:
  contents: write

jobs:
  package-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve tag (manual or from release)
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          fi
          echo "Using tag: $TAG"

      - name: Create plugin zip
        run: |
          PLUGDIR="apps/wp-plugin/G3D-Flow-Orchestrator"
          OUT="g3d-flow-orchestrator-${TAG}.zip"
          cd "$PLUGDIR/.."
          # Crea el zip en la RAÍZ del repo y excluye archivos de desarrollo
          zip -r "$GITHUB_WORKSPACE/$OUT" "G3D-Flow-Orchestrator" \
            -x "**/.git/**" "**/.github/**" "**/node_modules/**" "**/tests/**" \
               "**/*.map" "**/*.log" "**/.DS_Store" \
               "**/.phpstan*" "**/phpstan.neon" \
               "**/composer.*" "**/package-lock.json" \
               "**/.editorconfig" "**/.vscode/**"
          echo "ZIP_PATH=$GITHUB_WORKSPACE/$OUT" >> $GITHUB_ENV
          ls -lh "$GITHUB_WORKSPACE/$OUT"

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: ${{ env.ZIP_PATH }}
          fail_on_unmatched_files: true
