name: Repo · Sync labels
on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

# Permisos por defecto del workflow
permissions:
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest
    # Permisos necesarios para crear/actualizar etiquetas
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml   # ← nombre correcto del input
          dry-run: false
          skip-delete: true               # no borra etiquetas existentes
