name: Repo · Sync labels
on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

permissions:
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1            # ← sin "repository:" (usa este repo)
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml  # ← input correcto
          dry-run: false
          skip-delete: true
